remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Yolin Pages Site
author: tsai-yolin
description: "Welcome to my website!"

sass:
  sass_dir: "assets/css"
  style: compressed  # 壓縮 CSS 來提升加載速度

social_links:
  - name: "GitHub"
    url: "https://github.com/your-username"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/your-profile"
  - name: "Twitter"
    url: "https://twitter.com/your-handle"